using System.Text;
using Trebuchet.Compiler.Semantics;
using Trebuchet.Compiler.Syntax;
using static Trebuchet.Compiler.Semantics.Unifier;

namespace Trebuchet.Compiler.Backends;

/// <summary>
/// Lowers a checked program to a single C++20 header against trebuchet.hpp. Each module
/// becomes a namespace under <c>gen</c> that imports its dependencies with using-directives.
/// Records are structs with defaulted equality, unions are std::variant, shapes are abstract
/// classes, and services are classes held by treb::Rc. Suspend lowers to treb::Task
/// coroutines: a function whose effects include Suspend returns Task and is co_awaited,
/// by the same rule the C# emitter uses. The statement lowering matches the C# emitter.
/// </summary>
public sealed class CppEmitter
{
    private readonly ModuleSet _modules;
    private readonly TypeChecker _checker;
    private readonly List<ShapeT> _shapes = new();
    private readonly HashSet<FnT> _forcedAsync = new(ReferenceEqualityComparer.Instance);
    private bool _polyAsync;

    /// <summary>Whether calling this function may suspend: emitted as a Task coroutine and co_awaited.</summary>
    public bool Suspends(FnT f)
    {
        var o = f.Origin ?? f;
        if (_forcedAsync.Contains(o)) return true;
        if (o.Effects is null && !_checker.IsBuiltin(o) && !_checker.HasFrame(o)) return _polyAsync;
        return _checker.EffectsOf(f).Contains("Suspend");
    }

    private string Ret(FnT f) => Suspends(f) ? $"Task<{CppType(f.Return)}>" : CppType(f.Return);

    private static readonly HashSet<string> Keywords = new()
    {
        "alignas","alignof","asm","auto","bool","break","case","catch","char","char8_t","char16_t","char32_t","class","concept","const",
        "consteval","constexpr","constinit","const_cast","continue","co_await","co_return","co_yield","decltype","default","delete","do",
        "double","dynamic_cast","else","enum","explicit","export","extern","false","float","for","friend","goto","if","inline","int","long",
        "mutable","namespace","new","noexcept","nullptr","operator","private","protected","public","register","reinterpret_cast","requires",
        "return","short","signed","sizeof","static","static_assert","static_cast","struct","switch","template","this","thread_local","throw",
        "true","try","typedef","typeid","typename","union","unsigned","using","virtual","void","volatile","wchar_t","while",
        // runtime and libc names that would be shadowed or ambiguous
        "free","exit","abort","main","errno","stdin","stdout","stderr","time","clock","log","exp","div","remove","rename","min","max","sleep",
    };

    public CppEmitter(ModuleSet modules, TypeChecker checker)
    {
        _modules = modules;
        _checker = checker;
        foreach (var m in modules.Modules)
            foreach (var d in m.Decls)
                if (d is ShapeDecl sh) _shapes.Add(checker.ShapeTypeOf(sh));
        foreach (var m in modules.Modules)
            foreach (var d in m.Decls)
                if (d is ServiceDecl s)
                {
                    var st = checker.ServiceTypeOf(s);
                    foreach (var shape in _shapes.Where(h => checker.Satisfies(st, h)))
                        foreach (var (name, member) in shape.Members)
                            if (Suspends(member) && st.Methods.TryGetValue(name, out var impl)) _forcedAsync.Add(impl);
                }
    }

    public static string FindRuntimeDir()
    {
        var dir = AppContext.BaseDirectory;
        while (dir is not null)
        {
            var candidate = Path.Combine(dir, "src", "Trebuchet.Runtime.Cpp", "trebuchet.hpp");
            if (File.Exists(candidate)) return Path.GetDirectoryName(candidate)!;
            dir = Path.GetDirectoryName(dir);
        }
        var packaged = Path.Combine(AppContext.BaseDirectory, "runtime-cpp", "trebuchet.hpp");
        if (File.Exists(packaged)) return Path.GetDirectoryName(packaged)!;
        throw new InvalidOperationException("trebuchet.hpp not found above " + AppContext.BaseDirectory);
    }

    public IReadOnlyDictionary<string, string> Emit()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> by treb emit --target cpp </auto-generated>");
        sb.AppendLine("#pragma once");
        sb.AppendLine("#include \"trebuchet.hpp\"");
        sb.AppendLine();
        foreach (var m in Ordered()) EmitModule(sb, m);
        // Re-export every module into gen so a host can write `using namespace gen;`.
        sb.AppendLine("namespace gen {");
        foreach (var m in _modules.Modules) sb.AppendLine($"    using namespace gen::{Ns(m.Name)};");
        sb.AppendLine("}");
        return new Dictionary<string, string> { ["generated.hpp"] = sb.ToString() };
    }

    /// <summary>Modules in dependency order, so every import is declared before its importer.</summary>
    private List<Module> Ordered()
    {
        var result = new List<Module>();
        var seen = new HashSet<Module>();
        void Visit(Module m)
        {
            if (!seen.Add(m)) return;
            foreach (var imp in m.Imports) Visit(imp);
            result.Add(m);
        }
        foreach (var m in _modules.Modules) Visit(m);
        return result;
    }

    // ------------------------------------------------------------ naming and types

    public static string Ns(string moduleName) => string.Join("_", moduleName.Split('.').Select(Pascal));
    private static string Pascal(string s) => s.Length == 0 ? s : char.ToUpperInvariant(s[0]) + s[1..];
    private static string Id(string name) => Keywords.Contains(name) ? name + "_" : name;

    private static string Quote(string s)
    {
        var sb = new StringBuilder("\"");
        foreach (var ch in s)
            sb.Append(ch switch
            {
                '"' => "\\\"", '\\' => "\\\\", '\n' => "\\n", '\r' => "\\r", '\t' => "\\t", '\0' => "\\0",
                _ => ch.ToString(),
            });
        return sb.Append('"').ToString();
    }

    public string CppType(TType t)
    {
        t = Prune(t);
        return t switch
        {
            PrimT p => p.Name switch
            {
                "Int" => "std::int64_t", "Float" => "double", "Bool" => "bool", "String" => "std::string", "Unit" => "Unit",
                "Instant" => "Instant", "Never" => "Unit", _ => "Unit",
            },
            AppT a => $"{a.Ctor}<{string.Join(", ", a.Args.Select(CppType))}>",
            TupleT tt => $"std::tuple<{string.Join(", ", tt.Items.Select(CppType))}>",
            RecordT r when ReferenceEquals(r, BuiltinSignatures.Panic) => "PanicValue", // treb::Panic is the exception
            RecordT r => r.TypeArgs.Count == 0 ? r.Name : $"{r.Name}<{string.Join(", ", r.TypeArgs.Select(CppType))}>",
            UnionT u => u.TypeArgs.Count == 0 ? u.Name : $"{u.Name}<{string.Join(", ", u.TypeArgs.Select(CppType))}>",
            ParamT p => p.Name,
            ServiceT s => $"Rc<{s.Name}>",
            ShapeT h => $"Rc<{h.Name}>",
            FnT f => $"std::function<{Ret(f)}({string.Join(", ", f.Params.Select(CppType))})>",
            _ => "Unit",
        };
    }

    private string Params(IReadOnlyList<Param> ps, FnT t) =>
        string.Join(", ", ps.Select((p, i) => $"{CppType(t.Params[i])} {Id(p.Name)}"));

    // ------------------------------------------------------------ modules

    private void EmitModule(StringBuilder sb, Module m)
    {
        var ns = Ns(m.Name);
        var imports = string.Concat(m.Imports.Select(i => $"    using namespace gen::{Ns(i.Name)};\n"));
        var hashes = new StringBuilder();

        // Part 1: types.
        sb.AppendLine($"// ---- module {m.Name}");
        sb.AppendLine($"namespace gen::{ns} {{");
        sb.AppendLine("    using namespace treb;");
        sb.Append(imports);
        foreach (var d in m.Decls)
        {
            switch (d)
            {
                case RecordDecl r: EmitRecord(sb, hashes, r, m, ns); break;
                case UnionDecl u: EmitUnion(sb, hashes, u, ns); break;
                case ShapeDecl sh when !_checker.ShapeTypeOf(sh).IsClass: EmitShape(sb, sh); break;
                case ServiceDecl s: EmitServiceDecl(sb, s); break;
                case InstanceDecl inst: EmitInstanceDecl(sb, inst); break;
            }
        }
        sb.AppendLine("}");
        sb.Append(hashes);

        // Part 2: functions, service method bodies, roots.
        sb.AppendLine($"namespace gen::{ns} {{");
        foreach (var d in m.Decls)
        {
            if (d is FnDecl fn)
            {
                var type = (FnT)((ValueSym)_checker.ScopeOf(m).LookupLocalValue(fn.Signature.Name)!).Type;
                sb.AppendLine($"    {TemplateFor(type, fn.Signature.TypeParams)}{Ret(type)} {Id(fn.Signature.Name)}({DictParams(type, Params(fn.Signature.Params, type))});");
                if (_checker.PolyParamsOf(type).Count > 0)
                {
                    _polyAsync = true;
                    sb.AppendLine($"    {TemplateFor(type, fn.Signature.TypeParams)}Task<{CppType(type.Return)}> {Id(fn.Signature.Name)}Async({DictParams(type, Params(fn.Signature.Params, type))});");
                    _polyAsync = false;
                }
            }
            if (d is ExternDecl ex) EmitExtern(sb, ex, m);
            if (d is RootDecl root) EmitRootDecl(sb, root);
        }
        foreach (var d in m.Decls)
        {
            switch (d)
            {
                case ServiceDecl s: EmitServiceMethods(sb, s, m); break;
                case InstanceDecl inst: EmitInstanceMethods(sb, inst, m); break;
                case FnDecl fn: EmitFunction(sb, fn, m, null); break;
                case RootDecl root: EmitRoot(sb, root, m); break;
            }
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>Whether a type mentions the named record or union anywhere, which on C++ means the field must be boxed.</summary>
    private static bool MentionsType(TType t, string name)
    {
        t = Prune(t);
        return t switch
        {
            RecordT r => r.Name == name || r.Union?.Name == name || r.TypeArgs.Any(a => MentionsType(a, name)),
            UnionT u => u.Name == name || u.TypeArgs.Any(a => MentionsType(a, name)),
            AppT a => a.Args.Any(x => MentionsType(x, name)),
            FnT f => f.Params.Any(x => MentionsType(x, name)) || MentionsType(f.Return, name),
            _ => false,
        };
    }

    /// <summary>A field is boxed when its type mentions the record it belongs to, or the union its variant belongs to.</summary>
    public static bool IsBoxed(RecordT owner, string field)
    {
        var def = owner.Definition ?? owner;
        var self = def.Union?.Name ?? def.Name;
        var t = def.Field(field);
        return t is not null && MentionsType(t, self);
    }

    private string FieldType(RecordT owner, (string Name, TType Type) f) => IsBoxed(owner, f.Name) ? $"Box<{CppType(f.Type)}>" : CppType(f.Type);

    /// <summary>Template parameters for a function: its type parameters plus one dictionary type per constraint.</summary>
    private static string TemplateFor(FnT type, IReadOnlyList<string> typeParams)
    {
        var ps = typeParams.Select(p => "class " + p).ToList();
        foreach (var param in type.TypeParams)
            if (type.Constraints.TryGetValue(param, out var shapes))
                foreach (var shape in shapes) ps.Add($"class {shape}_{param}");
        return ps.Count == 0 ? "" : $"template <{string.Join(", ", ps)}> ";
    }

    private static string DictParams(FnT type, string declared)
    {
        var parts = new List<string>();
        foreach (var param in type.TypeParams)
            if (type.Constraints.TryGetValue(param, out var shapes))
                foreach (var shape in shapes) parts.Add($"{shape}_{param} __{shape}_{param}");
        if (parts.Count == 0) return declared;
        return declared.Length == 0 ? string.Join(", ", parts) : declared + ", " + string.Join(", ", parts);
    }

    /// <summary>The dictionary value for a shape at a type: a hidden parameter, a built-in instance, or a generated one.</summary>
    private string DictExpr(string shape, TType t)
    {
        t = Prune(t);
        if (t is ParamT p) return $"__{shape}_{p.Name}";
        if (BuiltinSignatures.HasBuiltinInstance(shape, t)) return $"Ord_{((PrimT)t).Name}{{}}";
        return $"{shape}_{TypeChecker.TypeKey(t)}{{}}";
    }

    private void EmitInstanceDecl(StringBuilder sb, InstanceDecl inst)
    {
        var name = $"{inst.Shape}_{TypeChecker.TypeKey(_checker.InstanceTargets[inst])}";
        sb.AppendLine($"    struct {name} {{");
        foreach (var method in inst.Methods)
        {
            var mt = _checker.InstanceMemberTypes[(inst, method.Signature.Name)];
            sb.AppendLine($"        {Ret(mt)} {Id(method.Signature.Name)}({Params(method.Signature.Params, mt)}) const;");
        }
        sb.AppendLine("    };");
    }

    private void EmitInstanceMethods(StringBuilder sb, InstanceDecl inst, Module m)
    {
        var name = $"{inst.Shape}_{TypeChecker.TypeKey(_checker.InstanceTargets[inst])}";
        foreach (var method in inst.Methods)
        {
            var mt = _checker.InstanceMemberTypes[(inst, method.Signature.Name)];
            sb.AppendLine($"    {Ret(mt)} {name}::{Id(method.Signature.Name)}({Params(method.Signature.Params, mt)}) const");
            sb.AppendLine("    {");
            var fe = new FnEmitter(this, m, mt.Return, 2, inMethod: true, coroutine: Suspends(mt));
            fe.EmitBlockInto(method.Body, FnEmitter.Target.Return, mt.Return);
            sb.Append(fe.Text);
            sb.AppendLine("    }");
        }
    }

    private static string Template(IReadOnlyList<string> typeParams) => typeParams.Count == 0 ? "" : $"template <{string.Join(", ", typeParams.Select(p => "class " + p))}> ";
    private static string TArgs(IReadOnlyList<string> typeParams) => typeParams.Count == 0 ? "" : $"<{string.Join(", ", typeParams)}>";

    private void EmitRecord(StringBuilder sb, StringBuilder hashes, RecordDecl r, Module m, string ns)
    {
        var rt = _checker.RecordTypeOf(r);
        var hasInit = r.Fields.Any(f => f.Init is not null);
        sb.AppendLine($"    {Template(r.TypeParams)}struct {r.Name} {{");
        foreach (var f in rt.Fields) sb.AppendLine($"        {FieldType(rt, f)} {Id(f.Name)};");
        if (hasInit)
        {
            sb.AppendLine($"        {r.Name}({string.Join(", ", rt.Fields.Select(f => $"{CppType(f.Type)} {Id(f.Name)}"))})");
            sb.AppendLine("        {");
            foreach (var f in r.Fields)
            {
                var ft = rt.Field(f.Name)!;
                if (f.Init is not null)
                {
                    sb.AppendLine("            {");
                    sb.AppendLine($"                auto value = {Id(f.Name)};");
                    var fe = new FnEmitter(this, m, ft, 4, inMethod: false);
                    fe.EmitInto(f.Init, FnEmitter.Target.Assign(Id(f.Name)), ft);
                    sb.Append(fe.Text);
                    sb.AppendLine("            }");
                }
                sb.AppendLine($"            this->{Id(f.Name)} = {Id(f.Name)};");
            }
            sb.AppendLine("        }");
        }
        sb.AppendLine($"        bool operator==(const {r.Name}&) const = default;");
        sb.AppendLine("    };");
        Hash(hashes, $"gen::{ns}::{r.Name}{TArgs(r.TypeParams)}", rt.Fields.Select(f => Id(f.Name)), r.TypeParams);
    }

    private static void Hash(StringBuilder hashes, string qualified, IEnumerable<string> fields, IReadOnlyList<string> typeParams)
    {
        var list = fields.ToList();
        var expr = list.Count == 0 ? "13" : $"treb::hashCombine(13, {string.Join(", ", list.Select(f => "r." + f))})";
        var template = typeParams.Count == 0 ? "template <>" : $"template <{string.Join(", ", typeParams.Select(p => "class " + p))}>";
        hashes.AppendLine($"{template} struct std::hash<{qualified}> {{ std::size_t operator()(const {qualified}& r) const {{ (void)r; return {expr}; }} }};");
    }

    private void EmitUnion(StringBuilder sb, StringBuilder hashes, UnionDecl u, string ns)
    {
        var ut = _checker.UnionTypeOf(u);
        var targs = TArgs(u.TypeParams);
        // The alias comes first over forward-declared variants, so a recursive variant can hold Box<Union>.
        foreach (var v in ut.Variants) sb.AppendLine($"    {Template(u.TypeParams)}struct {v.Name};");
        sb.AppendLine($"    {Template(u.TypeParams)}using {u.Name} = std::variant<{string.Join(", ", ut.Variants.Select(v => v.Name + targs))}>;");
        foreach (var v in ut.Variants)
        {
            sb.AppendLine($"    {Template(u.TypeParams)}struct {v.Name} {{");
            foreach (var f in v.Fields) sb.AppendLine($"        {FieldType(v, f)} {Id(f.Name)};");
            sb.AppendLine($"        bool operator==(const {v.Name}&) const = default;");
            sb.AppendLine("    };");
            Hash(hashes, $"gen::{ns}::{v.Name}{targs}", v.Fields.Select(f => Id(f.Name)), u.TypeParams);
        }
    }

    private void EmitShape(StringBuilder sb, ShapeDecl sh)
    {
        var ht = _checker.ShapeTypeOf(sh);
        sb.AppendLine($"    struct {sh.Name} {{");
        sb.AppendLine($"        virtual ~{sh.Name}() = default;");
        foreach (var member in sh.Members)
        {
            var mt = ht.Members[member.Name];
            sb.AppendLine($"        virtual {Ret(mt)} {Id(member.Name)}({Params(member.Params, mt)}) const = 0;");
        }
        sb.AppendLine("    };");
    }

    private List<ShapeT> Implemented(ServiceT st) => _shapes.Where(h => _checker.Satisfies(st, h)).ToList();

    private void EmitServiceDecl(StringBuilder sb, ServiceDecl s)
    {
        var st = _checker.ServiceTypeOf(s);
        var bases = Implemented(st);
        sb.AppendLine($"    struct {s.Name}{(bases.Count > 0 ? " : " + string.Join(", ", bases.Select(b => "public " + b.Name)) : "")} {{");
        foreach (var (name, type) in st.Dependencies) sb.AppendLine($"        {CppType(type)} {Id(name)};");
        if (st.Dependencies.Count > 0)
            sb.AppendLine($"        {s.Name}({string.Join(", ", st.Dependencies.Select(d => $"{CppType(d.Type)} {Id(d.Name)}"))}) : {string.Join(", ", st.Dependencies.Select(d => $"{Id(d.Name)}({Id(d.Name)})"))} {{}}");
        if (_checker.ReleaseOf(st) is { } release)
        {
            // Release runs when the last reference drops: `use` bindings, dependents, and roots all release through Rc.
            sb.AppendLine($"        ~{s.Name}() {{ try {{ {(Suspends(release) ? "release().get();" : "release();")} }} catch (...) {{}} }}");
        }
        foreach (var method in s.Methods)
        {
            var mt = st.Methods[method.Signature.Name];
            var overrides = bases.Any(b => b.Members.ContainsKey(method.Signature.Name)) ? " override" : "";
            sb.AppendLine($"        {Ret(mt)} {Id(method.Signature.Name)}({Params(method.Signature.Params, mt)}) const{overrides};");
        }
        sb.AppendLine("    };");
    }

    private void EmitServiceMethods(StringBuilder sb, ServiceDecl s, Module m)
    {
        var st = _checker.ServiceTypeOf(s);
        foreach (var method in s.Methods)
        {
            var mt = st.Methods[method.Signature.Name];
            sb.AppendLine($"    {Ret(mt)} {s.Name}::{Id(method.Signature.Name)}({Params(method.Signature.Params, mt)}) const");
            sb.AppendLine("    {");
            var fe = new FnEmitter(this, m, mt.Return, 2, inMethod: true, coroutine: Suspends(mt));
            fe.EmitBlockInto(method.Body, FnEmitter.Target.Return, mt.Return);
            sb.Append(fe.Text);
            sb.AppendLine("    }");
        }
    }

    private void EmitFunction(StringBuilder sb, FnDecl fn, Module m, string? _)
    {
        var type = (FnT)((ValueSym)_checker.ScopeOf(m).LookupLocalValue(fn.Signature.Name)!).Type;
        EmitFunctionVariant(sb, fn, m, type, fn.Signature.Name, polyAsync: false);
        if (_checker.PolyParamsOf(type).Count > 0)
            EmitFunctionVariant(sb, fn, m, type, fn.Signature.Name + "Async", polyAsync: true);
    }

    private void EmitFunctionVariant(StringBuilder sb, FnDecl fn, Module m, FnT type, string name, bool polyAsync)
    {
        var saved = _polyAsync;
        _polyAsync = polyAsync;
        var coroutine = Suspends(type) || polyAsync;
        var ret = coroutine ? $"Task<{CppType(type.Return)}>" : CppType(type.Return);
        sb.AppendLine($"    {TemplateFor(type, fn.Signature.TypeParams)}{ret} {Id(name)}({DictParams(type, Params(fn.Signature.Params, type))})");
        sb.AppendLine("    {");
        var fe = new FnEmitter(this, m, type.Return, 2, inMethod: false, coroutine: coroutine);
        fe.EmitBlockInto(fn.Body, FnEmitter.Target.Return, type.Return);
        sb.Append(fe.Text);
        sb.AppendLine("    }");
        _polyAsync = saved;
    }

    private void EmitExtern(StringBuilder sb, ExternDecl ex, Module m)
    {
        var type = (FnT)((ValueSym)_checker.ScopeOf(m).LookupLocalValue(ex.Signature.Name)!).Type;
        var binding = ex.Bindings.FirstOrDefault(b => b.Target == "cpp");
        var ret = Suspends(type) ? "co_return" : "return";
        sb.AppendLine($"    inline {Ret(type)} {Id(ex.Signature.Name)}({Params(ex.Signature.Params, type)})");
        sb.AppendLine("    {");
        if (binding is null)
        {
            sb.AppendLine($"        throw treb::Panic(\"extern {ex.Signature.Name} has no cpp binding\");");
            sb.AppendLine("    }");
            return;
        }
        var args = string.Join(", ", ex.Signature.Params.Select(p => Id(p.Name)));
        var isResult = Prune(type.Return) is AppT { Ctor: "Result" };
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine(isResult ? $"            {ret} treb::ok({binding.Symbol}({args}));" : $"            {ret} {binding.Symbol}({args});");
        sb.AppendLine("        }");
        foreach (var c in ex.Catches.Where(c => c.Target == "cpp"))
        {
            var unionType = CppType(((AppT)Prune(type.Return)).Args[1]);
            sb.AppendLine($"        catch (const {c.ExceptionType}& ex) {{ {ret} treb::error({unionType}{{{c.Variant}{{std::string(ex.what())}}}}); }}");
        }
        sb.AppendLine("        catch (const treb::Panic&) { throw; }");
        sb.AppendLine($"        catch (const std::exception& ex) {{ throw treb::Panic(std::string(\"extern {ex.Signature.Name}: \") + ex.what()); }}");
        sb.AppendLine("    }");
    }

    private void EmitRootDecl(StringBuilder sb, RootDecl root)
    {
        var entries = root.Entries.Where(e => e.Name is not null).ToList();
        sb.AppendLine($"    struct Root_{root.Name} {{");
        foreach (var e in entries) sb.AppendLine($"        {CppType(_checker.RootEntryTypes[(root, e.Name!)])} {Id(e.Name!)};");
        sb.AppendLine("    };");
        var rootAsync = _checker.RootEffects(root).Contains("Suspend");
        sb.AppendLine($"    {(rootAsync ? $"Task<Root_{root.Name}>" : $"Root_{root.Name}")} {Id(root.Name)}();");
    }

    private void EmitRoot(StringBuilder sb, RootDecl root, Module m)
    {
        var entries = root.Entries.Where(e => e.Name is not null).ToDictionary(e => e.Name!, e => e);
        var entryTypes = entries.Keys.ToDictionary(n => n, n => _checker.RootEntryTypes[(root, n)]);
        var rootAsync = _checker.RootEffects(root).Contains("Suspend");
        var fe = new FnEmitter(this, m, null, 2, inMethod: false, coroutine: rootAsync);
        var done = new HashSet<string>();
        var scope = _checker.ScopeOf(m);

        string Construct(ServiceT st, IReadOnlyDictionary<string, string> overrides)
        {
            var args = new List<string>();
            foreach (var (depName, depType) in st.Dependencies)
            {
                if (overrides.TryGetValue(depName, out var o)) { args.Add(o); continue; }
                if (entries.ContainsKey(depName)) { EmitEntry(depName); args.Add(Id(depName)); continue; }
                var typeName = (Prune(depType) as ServiceT)?.Name ?? (Prune(depType) as ShapeT)?.Name;
                var byType = entries.FirstOrDefault(e => e.Value.Value is TypeNameExpr te && te.Name == typeName);
                if (byType.Key is not null) { EmitEntry(byType.Key); args.Add(Id(byType.Key)); continue; }
                if (Prune(depType) is ServiceT implicitService) { args.Add(Construct(implicitService, new Dictionary<string, string>())); continue; }
                if (Prune(depType) is FnT factory && Prune(factory.Return) is ServiceT target && TypeChecker.PlanFactory(factory, target) is { } plan)
                {
                    // synthesised factory: a lambda capturing the root's locals by value
                    var ps = factory.Params.Select((t, i) => $"{CppType(t)} __p{i}").ToList();
                    var fill = new Dictionary<string, string>();
                    for (var i = 0; i < plan.Count; i++) fill[target.Dependencies[plan[i]].Name] = $"__p{i}";
                    args.Add($"[=]({string.Join(", ", ps)}) {{ return {Construct(target, fill)}; }}");
                    continue;
                }
                args.Add("{}");
            }
            return $"makeRc<{st.Name}>({string.Join(", ", args)})";
        }

        void EmitEntry(string name)
        {
            if (!done.Add(name)) return;
            var entry = entries[name];
            string value;
            if (entry.Value is TypeNameExpr tn && scope.LookupType(tn.Name) is ServiceT st)
                value = Construct(st, new Dictionary<string, string>());
            else if (entry.Value is CallExpr { Callee: TypeNameExpr ct, HasParens: false } c && scope.LookupType(ct.Name) is ServiceT cst)
            {
                var overrides = new Dictionary<string, string>();
                foreach (var a in c.BlockArgs.Where(a => a.Name is not null)) overrides[a.Name!] = fe.EmitExpr(a.Value, null);
                value = Construct(cst, overrides);
            }
            else value = fe.EmitExpr(entry.Value, entryTypes[name]);
            fe.Line($"{CppType(entryTypes[name])} {Id(name)} = {value};");
        }

        foreach (var name in entries.Keys) EmitEntry(name);
        fe.Line($"{(rootAsync ? "co_return" : "return")} Root_{root.Name}{{{string.Join(", ", entries.Keys.Select(Id))}}};");
        sb.AppendLine($"    {(rootAsync ? $"Task<Root_{root.Name}>" : $"Root_{root.Name}")} {Id(root.Name)}()");
        sb.AppendLine("    {");
        sb.Append(fe.Text);
        sb.AppendLine("    }");
    }

    // ------------------------------------------------------------ function bodies

    private sealed class FnEmitter
    {
        public readonly record struct Target(string Kind, string? Name)
        {
            public static readonly Target Return = new("return", null);
            public static readonly Target Discard = new("discard", null);
            public static Target Assign(string name) => new("assign", name);
        }

        private readonly CppEmitter _e;
        private readonly Module _m;
        private readonly TType? _returnType;
        private readonly bool _inMethod;
        private readonly bool _coroutine;
        private readonly StringBuilder _sb = new();
        private int _indent;
        private int _tmp;

        public FnEmitter(CppEmitter e, Module m, TType? returnType, int indent, bool inMethod, bool coroutine = false)
        {
            _e = e;
            _m = m;
            _returnType = returnType;
            _indent = indent;
            _inMethod = inMethod;
            _coroutine = coroutine;
        }

        private string ReturnKeyword => _coroutine ? "co_return" : "return";

        public string Text => _sb.ToString();
        public void Line(string s) => _sb.Append(new string(' ', _indent * 4)).AppendLine(s);
        private string Tmp(string hint = "t") => $"t_{hint}{++_tmp}";
        private TType TypeOf(Expr e) => _e._checker.ExprTypes.TryGetValue(e, out var t) ? t : PrimT.Unknown;
        private FnT? CalleeOf(CallExpr c) => _e._checker.CalleeOf.GetValueOrDefault(c);
        private string Pad() => new string(' ', _indent * 4);

        // ---- statements

        public void EmitBlockInto(Block block, Target target, TType? expected)
        {
            for (var i = 0; i < block.Stmts.Count; i++)
            {
                var s = block.Stmts[i];
                var last = i == block.Stmts.Count - 1;
                switch (s)
                {
                    case BindingStmt b:
                    {
                        var t = TypeOf(b.Value);
                        if (b.Value is IfExpr or MatchExpr)
                        {
                            var tv = Tmp("b");
                            Line($"std::optional<{_e.CppType(t)}> {tv};");
                            EmitInto(b.Value, Target.Assign(tv), t);
                            Line($"{_e.CppType(t)} {Id(b.Name)} = *{tv};");
                        }
                        else
                        {
                            var v = EmitExpr(b.Value, t);
                            Line($"{DeclType(t)} {Id(b.Name)} = {v};");
                        }
                        if (last) EmitTarget(target, "unit");
                        break;
                    }
                    case DestructureStmt ds:
                    {
                        var t = TypeOf(ds.Value);
                        var tmp = Tmp("d");
                        Line($"auto {tmp} = {EmitExpr(ds.Value, t)};");
                        var (_, bindings) = Pattern(ds.Pattern, t, tmp);
                        foreach (var b in bindings) Line(b);
                        if (last) EmitTarget(target, "unit");
                        break;
                    }
                    case UseStmt u:
                    {
                        var t = TypeOf(u.Value);
                        var v = EmitExpr(u.Value, t);
                        Line($"{DeclType(t)} {Id(u.Name)} = {v};  // released when the last Rc drops at block end");
                        if (last) EmitTarget(target, "unit");
                        break;
                    }
                    case ExprStmt es:
                        EmitInto(es.Value, last ? target : Target.Discard, last ? expected : null);
                        break;
                }
            }
            if (block.Stmts.Count == 0) EmitTarget(target, "unit");
        }

        private string DeclType(TType t) => Prune(t) is VarT ? "auto" : _e.CppType(t);

        private void EmitTarget(Target target, string value)
        {
            switch (target.Kind)
            {
                case "return": Line($"{ReturnKeyword} {value};"); break;
                case "assign": Line($"{target.Name} = {value};"); break;
                default: Line($"(void)({value});"); break;
            }
        }

        public void EmitInto(Expr e, Target target, TType? expected)
        {
            switch (e)
            {
                case IfExpr ifx:
                {
                    var cond = EmitExpr(ifx.Condition, PrimT.Bool);
                    Line($"if ({cond})");
                    Line("{");
                    _indent++;
                    EmitBlockInto(ifx.Then, ifx.Else is null ? Target.Discard : target, expected);
                    _indent--;
                    Line("}");
                    if (ifx.Else is not null)
                    {
                        Line("else");
                        Line("{");
                        _indent++;
                        EmitBlockInto(ifx.Else, target, expected);
                        _indent--;
                        Line("}");
                    }
                    else EmitTarget(target, "unit");
                    break;
                }
                case MatchExpr mx:
                {
                    var st = TypeOf(mx.Scrutinee);
                    var sv = Tmp("m");
                    var done = Tmp("matched");
                    Line($"auto {sv} = {EmitExpr(mx.Scrutinee, null)};");
                    Line($"bool {done} = false;");
                    foreach (var arm in mx.Arms)
                    {
                        var (cond, bindings) = Pattern(arm.Pattern, st, sv);
                        Line($"if (!{done} && ({cond}))");
                        Line("{");
                        _indent++;
                        foreach (var b in bindings) Line(b);
                        if (arm.Guard is not null)
                        {
                            // bindings are in scope for the guard; a false guard falls through to the next arm
                            Line($"if ({EmitExpr(arm.Guard, PrimT.Bool)})");
                            Line("{");
                            _indent++;
                        }
                        Line($"{done} = true;");
                        EmitBlockInto(arm.Body, target, expected);
                        if (arm.Guard is not null)
                        {
                            _indent--;
                            Line("}");
                        }
                        _indent--;
                        Line("}");
                    }
                    Line(target.Kind == "return" ? "throw treb::Panic(\"no match arm\");" : $"if (!{done}) throw treb::Panic(\"no match arm\");");
                    break;
                }
                default:
                {
                    var v = EmitExpr(e, expected);
                    EmitTarget(target, v);
                    break;
                }
            }
        }

        // ---- patterns: (condition, binding statements) over an access path

        private (string cond, List<string> bindings) Pattern(Syntax.Pattern p, TType type, string access)
        {
            type = Prune(type);
            var bindings = new List<string>();
            switch (p)
            {
                case WildcardPattern: return ("true", bindings);
                case BindPattern b:
                    bindings.Add($"auto {Id(b.Name)} = {access};");
                    return ("true", bindings);
                case LiteralPattern lit:
                    return ($"({access} == {EmitExpr(lit.Literal, type)})", bindings);
                case AsPattern ap:
                {
                    bindings.Add($"auto {Id(ap.Name)} = {access};");
                    var (c, bs) = Pattern(ap.Inner, type, access);
                    bindings.AddRange(bs);
                    return (c, bindings);
                }
                case TuplePattern tp when type is TupleT tt:
                {
                    var conds = new List<string>();
                    for (var i = 0; i < tp.Items.Count; i++)
                    {
                        var (c, bs) = Pattern(tp.Items[i], tt.Items[i], $"std::get<{i}>({access})");
                        if (c != "true") conds.Add(c);
                        bindings.AddRange(bs);
                    }
                    return (conds.Count == 0 ? "true" : string.Join(" && ", conds), bindings);
                }
                case ListPattern lp when type is AppT { Ctor: "Vector" } vec:
                {
                    var conds = new List<string> { lp.Rest is null ? $"{access}.size() == {lp.Items.Count}" : $"{access}.size() >= {lp.Items.Count}" };
                    for (var i = 0; i < lp.Items.Count; i++)
                    {
                        var (c, bs) = Pattern(lp.Items[i], vec.Args[0], $"{access}.get({i})");
                        if (c != "true") conds.Add(c);
                        bindings.AddRange(bs);
                    }
                    if (lp.Rest is BindPattern rb) bindings.Add($"auto {Id(rb.Name)} = drop({access}, {lp.Items.Count});");
                    return (string.Join(" && ", conds), bindings);
                }
                case VariantPattern vp:
                {
                    var conds = new List<string>();
                    IReadOnlyList<(string Name, TType Type)> fields;
                    string inner;
                    switch (type)
                    {
                        case AppT { Ctor: "Option" } o:
                            conds.Add(vp.Name == "Some" ? $"{access}.v.has_value()" : $"!{access}.v.has_value()");
                            fields = vp.Name == "Some" ? new[] { ("value", o.Args[0]) } : Array.Empty<(string, TType)>();
                            inner = $"(*{access}.v)";
                            break;
                        case AppT { Ctor: "Result" } r:
                            conds.Add(vp.Name == "Ok" ? $"{access}.ok" : $"!{access}.ok");
                            fields = vp.Name == "Ok" ? new[] { ("value", r.Args[0]) } : new[] { ("error", r.Args[1]) };
                            inner = vp.Name == "Ok" ? $"(*{access}.value)" : $"(*{access}.error)";
                            break;
                        case UnionT u:
                        case RecordT { Union: { } } and var _ when (u = ((RecordT)type).Union!) is not null:
                        {
                            var vname = vp.Name + GenericArgs(u.TypeArgs);
                            conds.Add($"std::holds_alternative<{vname}>({access})");
                            fields = u.Variant(vp.Name)?.Fields.ToList() ?? new List<(string, TType)>();
                            inner = $"std::get<{vname}>({access})";
                            break;
                        }
                        case RecordT rec:
                            fields = rec.Fields;
                            inner = access;
                            break;
                        default:
                            return ("true", bindings);
                    }
                    var variantRecord = type is UnionT vu ? vu.Variant(vp.Name) : (type as RecordT);
                    void MatchField(int i, Syntax.Pattern sub)
                    {
                        var (f, ft) = fields[i];
                        var subAccess = fields.Count == 1 && (type is AppT) ? inner : $"{inner}.{Id(f)}";
                        if (variantRecord is not null && type is not AppT && IsBoxed(variantRecord, f)) subAccess = $"(*{subAccess})";
                        var (c, bs) = Pattern(sub, ft, subAccess);
                        if (c != "true") conds.Add(c);
                        bindings.AddRange(bs);
                    }
                    for (var i = 0; i < vp.Args.Count; i++) MatchField(i, vp.Args[i]);
                    foreach (var (field, sub) in vp.NamedArgs) MatchField(fields.ToList().FindIndex(f => f.Name == field), sub);
                    return (conds.Count == 0 ? "true" : string.Join(" && ", conds), bindings);
                }
                default: throw new InvalidOperationException(p.GetType().Name);
            }
        }

        // ---- expressions

        public string EmitExpr(Expr e, TType? expected)
        {
            switch (e)
            {
                case IntLit i: return $"std::int64_t{{{i.Text}}}";
                case FloatLit f: return f.Text;
                case StringLit s: return $"std::string({Quote(s.Value)})";
                case BoolLit b: return b.Value ? "true" : "false";
                case NameExpr n: return Id(n.Name);
                case TypeNameExpr tn:
                {
                    var t = Prune(expected ?? TypeOf(tn));
                    if (t is UnionT u) return $"{_e.CppType(u)}{{{tn.Name}{GenericArgs(u.TypeArgs)}{{}}}}";
                    // a None whose Option type is known is spelled out, so template deduction sees an Option, not a NoneValue
                    if (tn.Name == "None" && t is AppT { Ctor: "Option" } o && Prune(o.Args[0]) is not VarT) return $"{_e.CppType(o)}::None()";
                    return tn.Name;
                }
                case TupleLit tl:
                {
                    var tt = Prune(TypeOf(tl)) as TupleT;
                    var items = tl.Items.Select((x, i) => EmitExpr(x, tt?.Items[i]));
                    return $"{(tt is null ? "std::make_tuple" : _e.CppType(tt))}{{{string.Join(", ", items)}}}";
                }
                case ListLit l:
                {
                    var t = Prune(expected ?? TypeOf(l));
                    var elem = t is AppT { Ctor: "Vector" } a ? a.Args[0] : PrimT.Unknown;
                    if (l.Items.Count == 0) return $"Vector<{_e.CppType(elem)}>{{}}";
                    return $"treb::vector<{_e.CppType(elem)}>({string.Join(", ", l.Items.Select(x => EmitExpr(x, elem)))})";
                }
                case MapLit ml:
                {
                    var t = Prune(expected ?? TypeOf(ml));
                    var (k, v) = t is AppT { Ctor: "Map" } a ? (a.Args[0], a.Args[1]) : (PrimT.Unknown, (TType)PrimT.Unknown);
                    var sb = new StringBuilder($"Map<{_e.CppType(k)}, {_e.CppType(v)}>{{}}");
                    foreach (var en in ml.Entries) sb.Append($".set({EmitExpr(en.Key, k)}, {EmitExpr(en.Value, v)})");
                    return sb.ToString();
                }
                case MemberExpr mem: return Member(mem, forCall: false);
                case CallExpr c: return Call(c, expected);
                case UnaryExpr un when un.Op != "supervise":
                    return un.Op == "not" ? $"(!{EmitExpr(un.Operand, PrimT.Bool)})" : $"(-{EmitExpr(un.Operand, null)})";
                case BinaryExpr b:
                {
                    var op = b.Op switch { "and" => "&&", "or" => "||", _ => b.Op };
                    if (_e._checker.OrdComparisons.TryGetValue(b, out var ordParam))
                        return $"(__Ord_{ordParam}.compare({EmitExpr(b.Left, null)}, {EmitExpr(b.Right, TypeOf(b.Left))}) {op} 0)";
                    var lt = TypeOf(b.Left);
                    return $"({EmitExpr(b.Left, null)} {op} {EmitExpr(b.Right, lt)})";
                }
                case UnaryExpr { Op: "supervise" } sv:
                {
                    var bodyType = TypeOf(sv.Operand);
                    var tv = Tmp("s");
                    var pv = Tmp("p");
                    var vt = _e.CppType(bodyType);
                    Line($"Result<{vt}, PanicValue> {tv};");
                    Line("try");
                    Line("{");
                    _indent++;
                    var body = EmitExpr(sv.Operand, bodyType);
                    Line($"{tv} = OkValue<{vt}>{{{body}}};");
                    _indent--;
                    Line("}");
                    Line($"catch (const treb::Panic& {pv}) {{ {tv} = ErrorValue<PanicValue>{{PanicValue{{{pv}.what()}}}}; }}");
                    return tv;
                }
                case PropagateExpr p:
                {
                    var inner = EmitExpr(p.Inner, null);
                    var rt = Prune(TypeOf(p.Inner)) as AppT ?? throw new InvalidOperationException("? on non-Result");
                    var tv = Tmp("r");
                    if (rt.Ctor == "Option")
                    {
                        Line($"auto {tv} = {inner};");
                        Line($"if (!{tv}.v.has_value()) {ReturnKeyword} NoneValue{{}};");
                        return $"(*{tv}.v)";
                    }
                    Line($"auto {tv} = {inner};");
                    Line($"if (!{tv}.ok) {ReturnKeyword} ErrorValue<{_e.CppType(rt.Args[1])}>{{*{tv}.error}};");
                    return $"(*{tv}.value)";
                }
                case LambdaExpr lam:
                {
                    var ft = Prune(TypeOf(lam)) as FnT ?? throw new InvalidOperationException("untyped lambda");
                    var ps = string.Join(", ", lam.Params.Select((p, i) => $"{_e.CppType(ft.Params[i])} {Id(p.Name)}"));
                    var isAsync = _e._checker.LambdaEffects(lam)?.Contains("Suspend") == true;
                    var inner = new FnEmitter(_e, _m, ft.Return, _indent + 1, _inMethod, coroutine: isAsync);
                    inner.EmitBlockInto(lam.Body, Target.Return, ft.Return);
                    var capture = _inMethod ? "[=, this]" : "[=]";
                    var lret = isAsync ? $"Task<{_e.CppType(ft.Return)}>" : _e.CppType(ft.Return);
                    return $"({capture}({ps}) -> {lret} {{\n{inner.Text}{Pad()}}})";
                }
                case IfExpr or MatchExpr:
                {
                    var t = expected ?? TypeOf(e);
                    var tv = Tmp("v");
                    Line($"std::optional<{_e.CppType(t)}> {tv};");
                    EmitInto(e, Target.Assign(tv), t);
                    return $"(*{tv})";
                }
                case WithExpr w:
                {
                    var target = EmitExpr(w.Target, null);
                    var rt = Prune(TypeOf(w.Target)) as RecordT;
                    var sb = new StringBuilder("([&]() { auto w_ = ").Append(target).Append("; ");
                    foreach (var f in w.Fields)
                    {
                        TType? ft = rt;
                        foreach (var seg in f.Path) ft = (Prune(ft ?? PrimT.Unknown) as RecordT)?.Field(seg);
                        sb.Append($"w_.{string.Join(".", f.Path.Select(Id))} = {EmitExpr(f.Value, ft)}; ");
                    }
                    return sb.Append("return w_; })()").ToString();
                }
                default:
                    throw new InvalidOperationException($"cannot emit {e.GetType().Name}");
            }
        }

        private string Member(MemberExpr mem, bool forCall)
        {
            var kind = _e._checker.MemberKinds.GetValueOrDefault(mem, TypeChecker.MemberKind.Sugar);
            switch (kind)
            {
                case TypeChecker.MemberKind.Namespace:
                {
                    var ns = Prune(TypeOf(mem.Target)) as NamespaceT ?? throw new InvalidOperationException("namespace member without namespace");
                    var label = ns.Scope.Label;
                    if (_e._modules.Find(label) is not null) return $"gen::{Ns(label)}::{Id(mem.Name)}";
                    if (label == "Cell") return mem.Name == "new" ? "treb::cellCreate" : $"Cell::{mem.Name}";
                    if (label == "Seq") return $"treb::seq::{mem.Name}";
                    if (label is "Instant") return $"Instant::{mem.Name}";
                    if (label is "sys" or "env" or "json") return $"treb::{label}::{mem.Name}";
                    return Prune(TypeOf(mem)) is UnionT u ? $"{_e.CppType(u)}{{{mem.Name}{GenericArgs(u.TypeArgs)}{{}}}}" : mem.Name;
                }
                case TypeChecker.MemberKind.Field when Prune(TypeOf(mem.Target)) is TupleT && int.TryParse(mem.Name, out var tupleIndex):
                    return $"std::get<{tupleIndex}>({EmitExpr(mem.Target, null)})";
                case TypeChecker.MemberKind.Field:
                {
                    var access = $"{EmitExpr(mem.Target, null)}.{Id(mem.Name)}";
                    return Prune(TypeOf(mem.Target)) is RecordT owner && IsBoxed(owner, mem.Name) ? $"(*{access})" : access;
                }
                case TypeChecker.MemberKind.Method:
                case TypeChecker.MemberKind.ShapeMember:
                    return $"{EmitExpr(mem.Target, null)}->{Id(mem.Name)}";
                default:
                    return forCall ? Id(mem.Name) : $"{Id(mem.Name)}({EmitExpr(mem.Target, null)})";
            }
        }

        private string Call(CallExpr c, TType? expected)
        {
            var callee = CalleeOf(c);
            var args = c.Args.Concat(c.BlockArgs).ToList();
            var typeArgs = c.TypeArgs.Count > 0
                ? "<" + string.Join(", ", c.TypeArgs.Select(t => _e.CppType(ResolveTypeRef(t)))) + ">"
                : "";

            if (callee is { Constructs: not null } || callee is { ConstructsService: not null })
            {
                // named arguments are reordered into declaration order; C++ has no keyword arguments
                var ordered = new string[callee.Params.Count];
                var next = 0;
                foreach (var a in args)
                {
                    var idx = a.Name is null ? next++ : callee.ParamNames.ToList().IndexOf(a.Name);
                    ordered[idx] = EmitExpr(a.Value, callee.Params[idx]);
                }
                var argList = string.Join(", ", ordered);
                if (callee.ConstructsService is { } svc) return $"makeRc<{svc.Name}>({argList})";
                var rec = callee.Constructs!;
                var returned = Prune(callee.Return);
                var targs = returned switch { RecordT rr => rr.TypeArgs, UnionT uu => uu.TypeArgs, _ => Array.Empty<TType>() };
                var construction = $"{rec.Name}{GenericArgs(targs)}{{{argList}}}";
                return rec.Union is not null && returned is UnionT ru ? $"{_e.CppType(ru)}{{{construction}}}" : construction;
            }
            if (_e._checker.CallTypeArgs.TryGetValue(c, out var callTypeArgs) && c.TypeArgs.Count == 0)
                typeArgs = GenericArgs(callTypeArgs);

            var argTexts = new List<string>();
            string head;
            if (_e._checker.ClassCalls.TryGetValue(c, out var classCall))
            {
                head = $"{_e.DictExpr(classCall.Shape, classCall.Type)}.{Id(classCall.Member)}";
                typeArgs = "";
            }
            else if (c.Callee is MemberExpr mem)
            {
                var kind = _e._checker.MemberKinds.GetValueOrDefault(mem, TypeChecker.MemberKind.Sugar);
                if (kind == TypeChecker.MemberKind.Sugar)
                {
                    argTexts.Add(EmitExpr(mem.Target, null));
                    head = Id(mem.Name);
                }
                else head = Member(mem, forCall: true);
            }
            else if (c.Callee is NameExpr n) head = Id(n.Name);
            else head = EmitExpr(c.Callee, null);

            var offset = argTexts.Count;
            for (var i = 0; i < args.Count; i++)
            {
                var paramType = callee is not null && i + offset < callee.Params.Count ? callee.Params[i + offset] : null;
                argTexts.Add(EmitExpr(args[i].Value, paramType));
            }
            if (head == "fail")
            {
                var t = expected is null || Prune(expected) is PrimT { Name: "Never" or "?" } ? (TType)PrimT.Unit : expected;
                return $"treb::fail<{_e.CppType(t)}>({string.Join(", ", argTexts)})";
            }

            var suspends = false;
            if (callee is not null && _e._checker.IsBuiltin(callee.Origin ?? callee))
            {
                var fnArgSuspends = args.Select(a => a.Value).Concat(c.Callee is MemberExpr sm && _e._checker.MemberKinds.GetValueOrDefault(sm) == TypeChecker.MemberKind.Sugar ? new[] { sm.Target } : Array.Empty<Expr>())
                    .Any(ArgSuspends);
                if (fnArgSuspends) { head += "Async"; suspends = true; }
                // a builtin that suspends by declaration, such as sleep
                else if (callee.Effects is not null && callee.Effects.Contains("Suspend")) suspends = true;
            }
            else if (callee is not null)
            {
                suspends = _e.Suspends(callee);
                var poly = _e._checker.PolyParamsOf(callee);
                if (poly.Count > 0)
                {
                    var offsetPoly = argTexts.Count - args.Count;
                    var anySuspends = poly.Any(i => i - offsetPoly >= 0 && i - offsetPoly < args.Count && ArgSuspends(args[i - offsetPoly].Value));
                    if (anySuspends) { head += "Async"; suspends = true; }
                }
            }
            if (_e._checker.CallDictionaries.TryGetValue(c, out var dictionaries))
                foreach (var (shape, dictType) in dictionaries) argTexts.Add(_e.DictExpr(shape, dictType));
            var text = $"{head}{typeArgs}({string.Join(", ", argTexts)})";
            return suspends ? $"(co_await {text})" : text;
        }

        private bool ArgSuspends(Expr arg)
        {
            if (arg is LambdaExpr lam) return _e._checker.LambdaEffects(lam)?.Contains("Suspend") == true;
            return Prune(TypeOf(arg)) is FnT f && _e.Suspends(f);
        }

        private string GenericArgs(IReadOnlyList<TType> args) => args.Count == 0 ? "" : $"<{string.Join(", ", args.Select(_e.CppType))}>";

        private TType ResolveTypeRef(TypeRef t)
        {
            var scope = _e._checker.ScopeOf(_m);
            return t switch
            {
                NamedType n when AppT.Arities.ContainsKey(AppT.Normalize(n.Name)) => new AppT(AppT.Normalize(n.Name), n.Args.Select(ResolveTypeRef).ToList()),
                NamedType n => scope.LookupType(n.Name) ?? PrimT.Unknown,
                FnType f => new FnT(f.Params.Select(ResolveTypeRef).ToList(), ResolveTypeRef(f.Return)),
                _ => PrimT.Unknown,
            };
        }
    }
}
